# Generated by Django 4.0.1 on 2022-01-10 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urls', '0002_alter_url_url_short'),
    ]

    operations = [
        migrations.AlterField(
            model_name='url',
            name='url_text',
            field=models.CharField(max_length=390),
        ),
    ]
